name: "Run linting and tests"

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        fast-glob: [2.2.7, 3.0.0, 3.2.2, 3.2.3]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: ./runTest.sh ${{ matrix.fast-glob }}
